package com.sleekydz86.catalog.global.exception;

public enum ErrorCode {
    VALIDATION_FAILED,
    RESOURCE_NOT_FOUND,
    RESOURCE_CONFLICT,
    CONNECTION_NOT_FOUND,
    METADATA_SET_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    EXTRACT_REQUEST_NOT_FOUND,
    INVALID_USER_STATUS,
    MIGRATION_FAILED,
    UNSUPPORTED_DDL_MAPPING,
    INTERNAL_SERVER_ERROR
}