package com.sleekydz86.catalog.global.exception;

public enum ErrorCode {
    VALIDATION_FAILED,
    RESOURCE_NOT_FOUND,
    RESOURCE_CONFLICT,
    CONNECTION_NOT_FOUND,
    CONNECTION_UNHEALTHY,
    METADATA_SET_NOT_FOUND,
    METADATA_SYNC_FAILED,
    CATEGORY_NOT_FOUND,
    EXTRACT_REQUEST_NOT_FOUND,
    EXTRACT_FAILED,
    INVALID_USER_STATUS,
    MIGRATION_FAILED,
    FILE_LOAD_FAILED,
    FILE_EXPORT_FAILED,
    UNSUPPORTED_DDL_MAPPING,
    EXTERNAL_SERVICE_FAILED,
    UNAUTHORIZED,
    FORBIDDEN,
    INTERNAL_SERVER_ERROR
}
